@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTc4ZTA2Ni1lZTU2LTQ1YmItODI5ZS05NDVlYzRmMWI1ZWYiLCJpYXQiOjE3NDkwNDQ5NzMsImV4cCI6MTc0OTA1OTM3M30.LGr4oJTZ14g30Tg96ckFBQAz3Ik4z2r_FRinTl3Xo-E
@categoryId = 36002350-caff-4297-8cfa-a03b0e4da7b5

# @name Users

## @name Create
POST http://localhost:3333/user
Content-Type: application/json
Authorization: Bearer UNIPAM_TEST

{
  "username": "unipam-security",
  "password": "123456"
}

###

## @name Authenticate
POST http://localhost:3333/user/auth
Content-Type: application/json

  {
    "username": "unipam-security",
    "password": "123456"
  }

###

# @name Target

## @name Create
POST http://localhost:3333/target
Content-Type: application/json

{
  "username": "unipam-security2",
  "email": "unipam2@unipam.com",
  "logId": "084859f3-0e45-4bdf-9b29-92bd9c3e6378"
}

###

## @name List
GET http://localhost:3333/target
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name AccessLog

## @name Create
POST http://localhost:3333/access-log
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "device": "iPhone",
  "ip": "0.0.0.0",
  "hash": "HOLQPK2NCM"
}

###

## @name List
GET http://localhost:3333/access-log
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name ExpectedTarget

## @name List
GET http://localhost:3333/expected-target
Content-Type: application/json
Authorization: Bearer {{token}}

###

## @name ListByCategoryId
GET http://localhost:3333/expected-target/category/{categoryId}
Content-Type: application/json
Authorization: Bearer {{token}}

###

## @name Create
POST http://localhost:3333/expected-target
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "unipam-security3",
  "email": "teste@unipam.edu.br"
}

###

# @name TestCategory

## @name Create
POST http://localhost:3333/test-category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Category 2"
}

###

## @name ListAll
GET http://localhost:3333/test-category
Content-Type: application/json
Authorization: Bearer {{token}}

###

## @name ListLastActive
GET http://localhost:3333/test-category/last-active
Content-Type: application/json
Authorization: Bearer {{token}}